FROM rails:4.2.4
MAINTAINER Kevin Hernandez <kevteg05@gmail.com>
RUN apt-get update
RUN apt-get install -y nodejs
RUN apt-get install -y npm
RUN mkdir -p /var/app
COPY Gemfile /var/app/Gemfile
COPY Gemfile.lock /var/app/Gemfile.lock
WORKDIR /var/app
RUN bundle install
CMD bundle exec rails s -b 0.0.0.0
